### ISSUE TITLE
Add another button to Engine Window to limit engine movetime (like new depth limit button) (feature request)

### ISSUE THREAD

**Issue by whelanh** [benini/scid#151] opened 2023-10-06 09:33 UTC
I really like the new button in the Engine Window that allows limiting engine by depth.  However the time it can take to reach a given depth can vary significantly throughout the game (large depth limit numbers can take forever in the opening, but considerably less time in the endgame).

Thus it would be nice to add another button that also allows limiting engine movetime. Then whichever limit comes first (depth or time) would come into effect.  I can do it manually by changing the /tcl/windows/engine.tcl line to "::engine::send $id Go [list $position [list {movetime 180000, depth 50}]]", but it would be nice to allow the buttons to do this (as is currently done with  """engine""send $id Go [list $position [set ::enginewin::limits_$id]]").

Finally it would be nice to allow the user to specify the limits rather than having to choose from the pre-specified choices as is done now with the depth limit button (again a user could just modify there own engine.tcl file if that is not possible).  

Scid has really seen some great improvements for which I am very grateful.  Kind regards.

**Comment by benini** [comment] 2023-10-06 22:06
>  I can do it manually by changing the /tcl/windows/engine.tcl line to "::engine::send $id Go [list $position [list {movetime 180000, depth 50}]]"

You can also add more options to the new button:
```
$btn.limits_menu add command -label "My limit" -command \
        "::enginewin::changeOption $id _go_limits \[list \[list movetime 180000 \] \[list depth 50 \] \]"
```

**Comment by whelanh** [comment] 2023-10-06 22:22
Ok....thank you very much.

**Comment by benini** [comment] 2024-03-05 08:27
Duplicate of:
https://sourceforge.net/p/scid/feature-requests/84/

**Closed as completed by benini** 2024-03-05 08:27 UTC
Labels: feature request
