### ISSUE TITLE
Scrambled Compressed Rows in submenus (e.g. preferences) and problems enlarging board

### ISSUE THREAD

**Issue by Willogically** [benini/scid#190] opened 2024-10-30 14:34 UTC
I have problems with compressed rows, making it difficult to read any text in submenus. Is there a way to fix this -see example in attachment. Also is there a way to make the board bigger -it's on maximum size in the added attachement, but I want it to fill the screen at least top down -also posted on Sourcefourge [https://sourceforge.net/p/scid/wiki/StartHere/].
![Screenshot SCID](https://github.com/user-attachments/assets/88c54521-ea4f-4a0c-b122-40eb64358d29)

**Comment by benini** [comment] 2024-10-31 10:35
Duplicate of:
https://sourceforge.net/p/scid/bugs/242/

**Closed as completed by benini** 2024-10-31 10:35 UTC
