### ISSUE TITLE
Add More Engine Move Arrows to Main Board

### ISSUE THREAD

**Issue by steve71** [benini/scid#121] opened 2023-04-30 15:09 UTC
It would be nice to have more move arrows on the main board showing the 2nd best move, 3rd best move, etc.  This can be tied into the number of engine lines spinbox in the bottom button bar of the engine window.  The user can therefore select how many arrows to be drawn.  One possible implementation:
![Screenshot_Engine_Move_Arrows](https://user-images.githubusercontent.com/1902337/235360849-a59f44de-1e26-4d27-a2b8-76715802edfd.png)

**Comment by benini** [comment] 2024-03-05 08:28
Duplicate of:
https://sourceforge.net/p/scid/feature-requests/102/

**Closed as completed by benini** 2024-03-05 08:28 UTC
Labels: feature request
